# Generated by Django 5.0.6 on 2024-08-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_or_sub', models.CharField(choices=[('Start', 'Start'), ('Sub', 'Sub')], default='Start', max_length=100)),
                ('minutes_played', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.player')),
                ('position_played', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.position')),
            ],
        ),
    ]
