# Generated by Django 5.0.6 on 2024-07-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_position_alter_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='postion',
            new_name='position',
        ),
    ]
