# Generated by Django 5.0.6 on 2024-07-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_rename_postion_position_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.team'),
        ),
    ]
