# Generated by Django 5.0.6 on 2024-08-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_match_game_week_teammetric_game_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.CharField(default=0.9995061728395062, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=0.9995061728395062, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metrics.competition', to_field='season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamlist',
            name='game_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamlist',
            name='season',
            field=models.ForeignKey(default=0.9995061728395062, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='metrics.competition', to_field='season'),
            preserve_default=False,
        ),
    ]
