# Generated by Django 5.0.6 on 2024-07-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_remove_match_team_alter_match_opponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='home_or_away',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Neutral', 'Neutarl')], default='Home', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metrics.competition'),
        ),
    ]
