# Generated by Django 5.0.6 on 2024-08-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_competition_season_match_season_teamlist_game_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='season',
            field=models.CharField(choices=[('2024/2025', '2024/2025')], default='2024/2025', max_length=100),
        ),
    ]
