# Generated by Django 5.0.6 on 2024-08-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_alter_competition_season_alter_match_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(choices=[('2024/2025', '2024/2025')], default='2024/2025', max_length=100),
        ),
    ]
